#!/bin/bash

strTrim=""
arGravity=()

# Suspicious Lists (https://firebog.net/)

arGravity+=("https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt           ")
arGravity+=("https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts              ")
arGravity+=("https://v.firebog.net/hosts/static/w3kbl.txt                                               ")
arGravity+=("https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt   ")
arGravity+=("https://someonewhocares.org/hosts/zero/hosts                                               ")
arGravity+=("https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts                             ")
arGravity+=("https://winhelp2002.mvps.org/hosts.txt                                                     ")
arGravity+=("https://v.firebog.net/hosts/neohostsbasic.txt                                              ")
arGravity+=("https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt             ")
arGravity+=("https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt                               ")

# Advertising Lists (https://firebog.net/)

arGravity+=("https://adaway.org/hosts.txt                                                                  ")
arGravity+=("https://v.firebog.net/hosts/AdguardDNS.txt                                                    ")
arGravity+=("https://v.firebog.net/hosts/Admiral.txt                                                       ")
arGravity+=("https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt                    ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt                                    ")
arGravity+=("https://v.firebog.net/hosts/Easylist.txt                                                      ")
arGravity+=("https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext ")
arGravity+=("https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts              ")
arGravity+=("https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts                              ")
arGravity+=("https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts                               ")

# Tracking & Telemetry Lists (https://firebog.net/)

arGravity+=("https://v.firebog.net/hosts/Easyprivacy.txt                                                     ")
arGravity+=("https://v.firebog.net/hosts/Prigent-Ads.txt                                                     ")
arGravity+=("https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts                 ")
arGravity+=("https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt         ")
arGravity+=("https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt                                      ")
arGravity+=("https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt                                      ")
arGravity+=("https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt                   ")
arGravity+=("https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt          ")
arGravity+=("https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt                   ")
arGravity+=("https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt              ")
arGravity+=("https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt                  ")

# Malicious Lists (https://firebog.net/)

arGravity+=("https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt                ")
arGravity+=("https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt                                                                              ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt                                                                           ")
arGravity+=("https://v.firebog.net/hosts/Prigent-Crypto.txt                                                                                                 ")
arGravity+=("https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt         ")
arGravity+=("https://phishing.army/download/phishing_army_blocklist_extended.txt                                                                            ")
arGravity+=("https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt                                                                   ")
arGravity+=("https://v.firebog.net/hosts/Shalla-mal.txt                                                                                                     ")
arGravity+=("https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt                                                                      ")
arGravity+=("https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts                                                                  ")
arGravity+=("https://urlhaus.abuse.ch/downloads/hostfile/                                                                                                   ")
arGravity+=("https://v.firebog.net/hosts/Prigent-Malware.txt                                                                                                ")
arGravity+=("https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt                                                          ")

# Other Lists (https://firebog.net/)

arGravity+=("https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser                                                                   ")
arGravity+=("https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_all.list                 ")
arGravity+=("https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list               ")
arGravity+=("https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt                                                   ")

# https://gist.github.com/rgstephens/e17f5730e9d172ce9725060b99375c03

arGravity+=("https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts                                                                        ")
arGravity+=("https://mirror1.malwaredomains.com/files/justdomains                                                                                    ")
arGravity+=("http://sysctl.org/cameleon/hosts                                                                                                        ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt                                                                        ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt                                                                              ")
arGravity+=("https://hosts-file.net/ad_servers.txt                                                                                                   ")
arGravity+=("https://hosts-file.net/grm.txt                                                                                                          ")
arGravity+=("https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts                                               ")
arGravity+=("https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts                                                          ")
arGravity+=("https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts                                                          ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt                                                                    ")
arGravity+=("https://hosts-file.net/exp.txt                                                                                                          ")
arGravity+=("https://hosts-file.net/emd.txt                                                                                                          ")
arGravity+=("https://hosts-file.net/psh.txt                                                                                                          ")
arGravity+=("https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt                                                                         ")
arGravity+=("https://www.malwaredomainlist.com/hostslist/hosts.txt                                                                                   ")
arGravity+=("https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt  ")
arGravity+=("https://v.firebog.net/hosts/Prigent-Malware.txt                                                                                         ")
arGravity+=("https://v.firebog.net/hosts/Prigent-Phishing.txt                                                                                        ")
arGravity+=("https://phishing.army/download/phishing_army_blocklist_extended.txt                                                                     ")
arGravity+=("https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt                                                            ")
arGravity+=("https://v.firebog.net/hosts/Shalla-mal.txt                                                                                              ")
arGravity+=("https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts                                                          ")
arGravity+=("https://www.squidblacklist.org/downloads/dg-malicious.acl                                                                               ")
arGravity+=("https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt                                                            ")
arGravity+=("https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt         ")
arGravity+=("https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt                                                   ")
arGravity+=("https://github.com/chadmayfield/pihole-blocklists/raw/master/lists/pi_blocklist_porn_all.list                                           ")
arGravity+=("https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list                              ")
arGravity+=("https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser                                                                               ")

# https://github.com/JavanXD/ya-pihole-list/blob/master/adlists.list.updater

arGravity+=("https://justdomains.github.io/blocklists/lists/easylist-justdomains.txt                                                      ")
arGravity+=("https://justdomains.github.io/blocklists/lists/easyprivacy-justdomains.txt                                                   ")
arGravity+=("https://justdomains.github.io/blocklists/lists/adguarddns-justdomains.txt                                                    ")
arGravity+=("https://justdomains.github.io/blocklists/lists/nocoin-justdomains.txt                                                        ")
arGravity+=("https://raw.githubusercontent.com/dfederlein/dnsbl-dfed/master/spotifyads.txt                                                ")
arGravity+=("https://raw.githubusercontent.com/hectorm/hmirror/master/data/spam404.com/list.txt                                           ")
arGravity+=("https://raw.githubusercontent.com/hectorm/hmirror/master/data/adaway.org/list.txt                                            ")
arGravity+=("https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe                                      ")
arGravity+=("https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails                                             ")
arGravity+=("https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/dnscrypt/spy.txt                                   ")
arGravity+=("https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/adservers.txt                      ")
arGravity+=("https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts                                                             ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt                                                                   ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt                                                             ")
arGravity+=("https://urlhaus.abuse.ch/downloads/hostfile/                                                                                 ")
arGravity+=("https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt                                                            ")
arGravity+=("https://dbl.oisd.nl/                                                                                                         ")

# Prevent Trackers and Malwares (https://filterlists.com/)

arGravity+=("https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/adservers-and-trackers.txt                                  ")
arGravity+=("https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt                                                                         ")
arGravity+=("https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt                                                                       ")
arGravity+=("https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt                                                                   ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt                                                                                     ")
arGravity+=("https://gitlab.com/my-privacy-dns/matrix/matrix/-/raw/master/source/tracking/domains.list                                                            ")
arGravity+=("https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardApps.txt                                                                          ")
arGravity+=("https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileAds.txt                                                                     ")
arGravity+=("https://raw.githubusercontent.com/FadeMind/hosts.extras/master/StreamingAds/hosts                                                                    ")
arGravity+=("https://raw.githubusercontent.com/w13d/adblockListABP-PiHole/master/Spotify.txt                                                                      ")
arGravity+=("https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/adservers-and-trackers.txt                                  ")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/AdAway-Default-Blocklist.txt                ")
arGravity+=("https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt                                                                                           ")
arGravity+=("https://v.firebog.net/hosts/Easyprivacy.txt                                                                                                          ")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/FadeMind-addSpam.txt                        ")
arGravity+=("https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list                                 ")

# Prevent Analytics (https://filterlists.com/)

arGravity+=("https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt                                                                   ")
arGravity+=("https://raw.githubusercontent.com/mitchellkrogza/Stop.Google.Analytics.Ghost.Spam.HOWTO/master/output/domains/INACTIVE/list                          ")
arGravity+=("https://raw.githubusercontent.com/nickspaargaren/no-google/master/categories/analytics.txt                                                           ")
arGravity+=("https://raw.githubusercontent.com/nickspaargaren/no-google/master/categories/analyticsparsed                                                         ")
arGravity+=("https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_facebook0.txt                                            ")
arGravity+=("https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt                                                                            ")

# Prevent Spyware (https://filterlists.com/)

arGravity+=("https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileSpyware.txt                                                                 ")
arGravity+=("https://raw.githubusercontent.com/XionKzn/PiHole-Lists/master/PiHole_HOSTS_Spyware.txt                                                               ")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/WindowsSpyBlocker81.txt                     ")
arGravity+=("https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt                                                              ")

# Prevent Coinmining network (https://filterlists.com/)

arGravity+=("https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list.txt                                                                                     ")
arGravity+=("https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt                                                                             ")
arGravity+=("https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts                                                                                        ")
arGravity+=("https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts_optional                                                                               ")
arGravity+=("https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt                                                                           ")
arGravity+=("https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/nocoin.txt                                                                 ")

# Prevent Ransomware (https://filterlists.com/)

arGravity+=("https://raw.githubusercontent.com/pirat28/IHateTracker/master/iHateTracker.txt                                                                       ")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/CryptoWall-Ransomware-C2-Domain-blocklist.tx")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/Locky-Ransomware-C2-Domain-Blocklist.txt    ")
arGravity+=("https://raw.githubusercontent.com/XionKzn/PiHole-Lists/master/Cerber_Ransomware.txt                                                                  ")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/Ransomware-Domain-Blocklist.txt             ")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/TeslaCrypt-Ransomware-C2-Domain-Blocklist.tx")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/TeslaCrypt-Ransomware-Payment-Sites-Domain-B")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/TorrentLocker-Ransomware-C2-Domain-Blocklist")
arGravity+=("https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/TorrentLocker-Ransomware-Payment-Sites-Domai")
arGravity+=("https://gitlab.com/Kurobeats/phishing_hosts/raw/master/hosts                                                                                         ")
arGravity+=("https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/master/src/hosts.txt                                                                  ")

for url in ${arGravity[*]}; do
  strTrim=$(echo -e "${url}" | tr -d '[:space:]')
  echo "Test >>$strTrim<<"
done
