#!/bin/sh
# Mini DLNA
### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

deamonPID=""
deamonNAM="minidlnad"
deamonLOC="/usr/local/sbin/$deamonNAM"
deamonSRV="minidlna"
deamoncnf="/home/test/Documents/TEST/.minidlna/minidlna.conf"

case "$1" in
  "start")
    deamonPID=$(/bin/pidof $deamonNAM)
    if [ $deamonPID ];
    then
      echo "Already running [$deamonPID]"
    else
      sudo $deamonLOC -f $deamonCNF
      deamonPID=$(/bin/pidof $deamonNAM)
      echo "Started [$deamonPID]"
    fi
  ;;
  "stop")
    deamonPID=$(/bin/pidof $deamonNAM)
    if [ $deamonPID ];
    then
      echo "Stopped [$deamonPID]"
      sudo kill -SIGTERM $deamonPID
    else
      echo "Already Stopped"
    fi
  ;;
  "restart")
    sudo service $deamonSRV stop
    sudo $deamonLOC -f $deamonCNF
    deamonPID=$(/bin/pidof $deamonNAM)
    echo "Restarted [$deamonPID]"
  ;;
  "status")
    deamonPID=$(/bin/pidof $deamonNAM)
    if [ $deamonPID ];
    then
      echo "Running [$deamonPID"]
    else
      echo "Stopped"
    fi
  ;;
  "rescan")
    sudo service $deamonSRV stop
    sudo $deamonLOC -R -f $deamonCNF
    deamonPID=$(/bin/pidof $deamonNAM)
    echo "Rescanning [$deamonPID]"
  ;;
  *)
    echo "Usage: $0 { start | stop | restart | status | rescan }"
  ;;
esac

exit 0